const playersData = [
// {'player_id': 540579,
//   'team_id': 6,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/3/540579.png',
//   'name': 'Oliver Skipp',
//   'position': 26,
//   'detailed_position': 149,
//   'position_name': 'Defensive Midfield',
//   'broad_position': 'Midfielder',
//   'average_rating': 6.71},
//  {'player_id': 1744,
//   'team_id': 6,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/16/1744.png',
//   'name': 'Pierre-Emile Højbjerg',
//   'position': 26,
//   'detailed_position': 153,
//   'position_name': 'Central Midfield',
//   'broad_position': 'Midfielder',
//   'average_rating': 6.87},
{'player_id': 32777506,
'team_id': 6,
'image_path': 'https://cdn.sportmonks.com/images/soccer/players/2/32777506.png',
'name': 'Destiny Udogie',
'position': 25,
'detailed_position': 155,
'position_name': 'Left Back',
'broad_position': 'Defender',
'average_rating': 7.31},
{'player_id': 37296248,
'team_id': 6,
'image_path': 'https://cdn.sportmonks.com/images/soccer/players/24/37296248.png',
'name': 'Micky van de Ven',
'position': 25,
'detailed_position': 148,
'position_name': 'Centre Back',
'broad_position': 'Defender',
'average_rating': 7.24},
 {'player_id': 4313,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/25/4313.png',
  'name': 'Heung-min Son',
  'position': 27,
  'detailed_position': 152,
  'position_name': 'Left Wing',
  'broad_position': 'Attacker',
  'average_rating': 7.88},
 {'player_id': 96870,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/6/96870.png',
  'name': 'Yves Bissouma',
  'position': 26,
  'detailed_position': 153,
  'position_name': 'Central Midfield',
  'broad_position': 'Midfielder',
  'average_rating': 7.48},
 {'player_id': 219633,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/17/219633.png',
  'name': 'Richarlison',
  'position': 27,
  'detailed_position': 151,
  'position_name': 'Centre Forward',
  'broad_position': 'Attacker',
  'average_rating': 6.78},
 {'player_id': 6838,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/22/6838.png',
  'name': 'James Maddison',
  'position': 26,
  'detailed_position': 150,
  'position_name': 'Attacking Midfield',
  'broad_position': 'Midfielder',
  'average_rating': 8.21},
 {'player_id': 133779,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/19/133779.png',
  'name': 'Guglielmo Vicario',
  'position': 24,
  'detailed_position': 24,
  'position_name': 'Goalkeeper',
  'broad_position': 'Goalkeeper',
  'average_rating': 7.38},
 {'player_id': 333731,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/3/333731.png',
  'name': 'Cristian Romero',
  'position': 25,
  'detailed_position': 148,
  'position_name': 'Centre Back',
  'broad_position': 'Defender',
  'average_rating': 7.54},
 {'player_id': 14338024,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/8/14338024.png',
  'name': 'Dejan Kulusevski',
  'position': 27,
  'detailed_position': 156,
  'position_name': 'Right Wing',
  'broad_position': 'Attacker',
  'average_rating': 7.38},
 {'player_id': 8456257,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/1/8456257.png',
  'name': 'Pedro Porro',
  'position': 25,
  'detailed_position': 154,
  'position_name': 'Right Back',
  'broad_position': 'Defender',
  'average_rating': 7.69},
//  {'player_id': 125482,
//   'team_id': 6,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/10/125482.png',
//   'name': 'Manor Solomon',
//   'position': 27,
//   'detailed_position': 152,
//   'position_name': 'Left Wing',
//   'broad_position': 'Attacker',
//   'average_rating': 7.42},
 {'player_id': 37342694,
  'team_id': 6,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/6/37342694.png',
  'name': 'Pape Matar Sarr',
  'position': 26,
  'detailed_position': 153,
  'position_name': 'Central Midfield',
  'broad_position': 'Midfielder',
  'average_rating': 7.48},
//  {'player_id': 989,
//   'team_id': 6,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/29/989.png',
//   'name': 'Ben Davies',
//   'position': 25,
//   'detailed_position': 155,
//   'position_name': 'Left Back',
//   'broad_position': 'Defender',
//   'average_rating': 6.89},
//  {'player_id': 37568165,
//   'team_id': 6,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/5/37568165.png',
//   'name': 'Alejo Véliz',
//   'position': 27,
//   'detailed_position': 151,
//   'position_name': 'Centre Forward',
//   'broad_position': 'Attacker',
//   'average_rating': 6.43},
{'player_id': 1078,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/22/1078.png',
  'name': 'Andrew Robertson',
  'position': 25,
  'detailed_position': 155,
  'position_name': 'Left Back',
  'broad_position': 'Defender',
  'average_rating': 7.3},
 {'player_id': 129820,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/28/129820.png',
  'name': 'Alisson',
  'position': 24,
  'detailed_position': 24,
  'position_name': 'Goalkeeper',
  'broad_position': 'Goalkeeper',
  'average_rating': 7.58},
  {'player_id': 1920,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/0/1920.png',
  'name': 'Joël Matip',
  'position': 25,
  'detailed_position': 148,
  'position_name': 'Centre Back',
  'broad_position': 'Defender',
  'average_rating': 7.14},
//  {'player_id': 309344,
//   'team_id': 8,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/0/309344.png',
//   'name': 'Wataru Endo',
//   'position': 26,
//   'detailed_position': 149,
//   'position_name': 'Defensive Midfield',
//   'broad_position': 'Midfielder',
//   'average_rating': 6.56},
 {'player_id': 1743,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/15/1743.png',
  'name': 'Virgil van Dijk',
  'position': 25,
  'detailed_position': 148,
  'position_name': 'Centre Back',
  'broad_position': 'Defender',
  'average_rating': 7.34},
  {'player_id': 1453,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/13/1453.png',
  'name': 'Joe Gomez',
  'position': 25,
  'detailed_position': 148,
  'position_name': 'Centre Back',
  'broad_position': 'Defender',
  'average_rating': 7.16},
//  {'player_id': 100556,
//   'team_id': 8,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/12/100556.png',
//   'name': 'Ibrahima Konaté',
//   'position': 25,
//   'detailed_position': 148,
//   'position_name': 'Centre Back',
//   'broad_position': 'Defender',
//   'average_rating': 7.06},
 {'player_id': 241036,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/12/241036.png',
  'name': 'Luis Díaz',
  'position': 27,
  'detailed_position': 152,
  'position_name': 'Left Wing',
  'broad_position': 'Attacker',
  'average_rating': 7.07},
  {'player_id': 4545513,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/9/4545513.png',
  'name': 'Curtis Jones',
  'position': 26,
  'detailed_position': 26,
  'position_name': 'Midfielder',
  'broad_position': 'Midfielder',
  'average_rating': 6.47},
 {'player_id': 216612,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/4/216612.png',
  'name': 'Alexis Mac Allister',
  'position': 26,
  'detailed_position': 153,
  'position_name': 'Central Midfield',
  'broad_position': 'Midfielder',
  'average_rating': 7.1},
  {'player_id': 785998,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/14/785998.png',
  'name': 'Dominik Szoboszlai',
  'position': 26,
  'detailed_position': 153,
  'position_name': 'Central Midfield',
  'broad_position': 'Midfielder',
  'average_rating': 7.39},
  {'player_id': 30062,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/14/30062.png',
  'name': 'Cody Gakpo',
  'position': 27,
  'detailed_position': 152,
  'position_name': 'Left Wing',
  'broad_position': 'Attacker',
  'average_rating': 6.97},
 {'player_id': 4125,
  'team_id': 8,
  'image_path': 'https://cdn.sportmonks.com/images/soccer/players/29/4125.png',
  'name': 'Mohamed Salah',
  'position': 27,
  'detailed_position': 156,
  'position_name': 'Right Wing',
  'broad_position': 'Attacker',
  'average_rating': 7.78},
//  {'player_id': 159917,
//   'team_id': 8,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/13/159917.png',
//   'name': 'Diogo Jota',
//   'position': 27,
//   'detailed_position': 27,
//   'position_name': 'Attacker',
//   'broad_position': 'Attacker',
//   'average_rating': 7.07},
//  {'player_id': 5270462,
//   'team_id': 8,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/30/5270462.png',
//   'name': 'Ryan Gravenberch',
//   'position': 26,
//   'detailed_position': 153,
//   'position_name': 'Central Midfield',
//   'broad_position': 'Midfielder',
//   'average_rating': 6.43},
//  {'player_id': 1917,
//   'team_id': 8,
//   'image_path': 'https://cdn.sportmonks.com/images/soccer/players/29/1917.png',
//   'name': 'Trent Alexander-Arnold',
//   'position': 25,
//   'detailed_position': 154,
//   'position_name': 'Right Back',
//   'broad_position': 'Defender',
//   'average_rating': 6.96}
]

export default playersData;
